database_url: "YOUR_DATABASE_URL"
base_url: "BASE_URL"
slurm_token_helper_url: "TOKEN_HELPER_URL"
slurm_restful_base_url: "RESTFUL_NODE_URL"
slurm_restful_version: "v0.0.43"
debug:
oauth_proxy_base_url:
oauth_proxy_secret:
google_oauth_client_id:
google_oauth_client_secret:
github_oauth_client_id:
github_oauth_client_secret:
nycu_oauth_client_id:
nycu_oauth_client_secret:
casbin_model_source:
casbin_policy_source:
redis_url:
allow_origins:
  - origin1
  - origin2
preset_user:
  'YOUR_EMAIL':
    role: admin